//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ultimate.rc
//
#define IDPREV                          3
#define IDEAS                           3
#define ID_NEXT                         3
#define IDNEXT                          4
#define ID_PREV                         4
#define IDINDIRECTS                     4
#define IDFATENTRIES                    5
#define IDLFN_CLEAR                     6
#define IDDOUCASE                       6
#define IDSFN_CLEAR                     7
#define IDFATENTRIES2                   7
#define IDEXFATCONVERT                  7
#define IDTIME                          8
#define IDSFN_CLEAR1                    8
#define ID_ENTRY_CLEAR                  8
#define IDDATE                          9
#define ID_FAT_ATTRIB                   10
#define IDDELLFN                        11
#define IDD_ABOUTBOX                    100
#define IDD_ULTIMATE_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   129
#define IDD_MBR                         130
#define IDD_GPT                         131
#define IDD_MBR_MT                      132
#define IDD_MBR_ENTRY                   133
#define IDD_GPT_ENTRY                   134
#define IDD_FAT                         135
#define IDB_FOLDER                      135
#define IDB_FILE                        136
#define IDD_LEAN                        136
#define IDB_DELETED                     137
#define IDD_FAT_ENTRY                   137
#define IDB_SYMBOLIC                    138
#define IDD_LEAN_ENTRY                  138
#define IDD_ATTRIBUTE                   139
#define IDD_LEAN_TIME                   140
#define IDD_SFS                         141
#define IDB_MAIN_ICON                   141
#define IDD_SFS_ENTRY                   142
#define IDB_LABEL                       142
#define IDD_FYSOS_SIG                   143
#define IDB_DEVICE                      143
#define IDD_SETTINGS                    144
#define IDB_FOLDER_HIDDEN               144
#define IDD_EMBR                        145
#define IDB_FILE_HIDDEN                 145
#define IDD_EMBR_ENTRY                  146
#define IDD_FAT32_INFO                  147
#define IDD_FAT32_ENTRY                 148
#define IDD_FYSFS                       149
#define IDD_FYSFS_ENTRY                 150
#define IDD_VHD                         151
#define IDD_UNKNOWN                     152
#define IDD_NEW_FILE                    153
#define IDD_NEW_PART                    154
#define IDD_ISO_PVD                     155
#define IDD_ISO_BVD                     156
#define IDD_ISO_TIME                    157
#define IDD_ISO_SVD                     158
#define IDD_ISO_ENTRY                   159
#define IDD_FAT_FORMAT                  160
#define IDD_FAT_CLUSTERS                161
#define IDD_SFS_FORMAT                  162
#define IDD_MODELESS                    163
#define IDD_LEAN_EAS                    164
#define ID_LEAN_CHECK                   165
#define IDD_EXT2                        165
#define IDD_EXT2_DYN                    166
#define ID_ISO_CHECK                    167
#define IDD_EXT2_GRP                    167
#define IDD_EXT2_ENTRY                  168
#define IDD_ULTIMATE_RESIZE             169
#define IDD_EXFAT                       170
#define IDD_EXFAT_ENTRY                 171
#define IDD_VIEW_BITMAP                 172
#define IDD_EXFAT_UCASE                 173
#define IDD_NTFS                        174
#define IDD_FIND                        175
#define IDD_NTFS_ENTRY                  176
#define IDD_GET_IMAGE                   177
#define IDD_LEAN_FORMAT                 178
#define IDD_LEAN_JOURNAL                179
#define IDD_ISO_BEA                     180
#define IDD_ISO_NSR                     181
#define IDD_UDF_TAG                     182
#define IDD_VOLUME_NAME                 183
#define IDD_GPT_GUID                    195
#define IDD_VDI                         196
#define IDD_FYSFS_FORMAT                197
#define IDD_FSZ                         198
#define IDD_LEAN_INDIRECT               199
#define IDD_LEAN_SYMBOLIC               200
#define IDC_IMAGE_BAR                   1002
#define IDC_PAGES                       1005
#define IDC_TABS                        1007
#define ID_BROWSE                       1010
#define IDCLEAR                         1011
#define IDC_FORCE_MBR                   1012
#define IDC_MBR_PAGES                   1013
#define IDC_FORCE_GPT                   1013
#define IDC_MBR_BOOT_ID                 1014
#define IDC_FORCE_GPT_ENUM              1014
#define IDC_MBR_SYS_ID                  1015
#define IDC_FORCE_READONLY              1015
#define IDC_MBR_START_LBA               1016
#define IDC_CLEAR_MRU                   1016
#define IDC_FORCE_NO_MBR                1016
#define IDC_MBR_SIZE                    1017
#define IDC_FORCE_FYSOS                 1017
#define ID_MBR_APPLY                    1018
#define IDC_MBR_BEGIN_CYL               1019
#define IDC_MBR_BEGIN_HEAD              1020
#define IDC_MBR_BEGIN_SECT              1021
#define IDC_MBR_END_CYL                 1022
#define IDC_MBR_END_HEAD                1023
#define IDC_MBR_END_SECT                1024
#define IDC_MBR_BEGIN_UPDATE            1025
#define IDC_MBR_END_UPDATE              1026
#define IDC_MBR_DUMP                    1026
#define IDC_MBR_OVERWRITE               1027
#define IDUPDATE_MBR                    1028
#define IDUPDATE_MBR_SIG                1029
#define IDC_SYS_STR                     1029
#define IDC_SPT                         1030
#define IDC_HEAD_COUNT                  1031
#define IDC_GPT_SIG                     1031
#define IDC_GPT_VERSION                 1032
#define IDC_MBR_OVERWRITE_ID            1032
#define IDC_CYL_COUNT                   1032
#define IDC_GPT_HDR_SIZE                1033
#define IDC_ID_SIG                      1033
#define IDC_GPT_CRC32                   1034
#define IDC_ID_ZERO                     1034
#define IDC_GPT_RSVD                    1035
#define IDC_MBR_LEGACY_GPT              1035
#define IDC_GPT_PRIMARY_LBA             1036
#define IDUPDATE_MBR_SIG2               1036
#define IDPREPEND_MBR                   1036
#define IDC_GPT_BACKUP_LBA              1037
#define IDUPDATE_MBR2                   1037
#define IDEXTRACT                       1037
#define IDC_GPT_FIRST_LBA               1038
#define IDC_GPT_LAST_LBA                1039
#define IDC_GPT_GUID                    1040
#define IDC_GPT_ENTRY_OFFSET            1041
#define IDC_GPT_ENTRY_COUNT             1042
#define IDC_GPT_ENTRY_SIZE              1043
#define IDC_GPT_ENTRY_CRC32             1044
#define IDC_GPT_DUMP                    1045
#define ID_GPT_APPLY                    1046
#define IDC_GPT_PAGES                   1047
#define IDC_END_DISP                    1048
#define IDC_MID_DISP                    1049
#define IDC_START_DISP                  1050
#define IDC_SIG_CHARS                   1051
#define IDC_GPT_VERSION_NUM             1052
#define IDC_CRC_BUTTON                  1053
#define IDC_ECRC_BUTTON                 1054
#define IDC_SECT_SIZE                   1054
#define IDC_GPTE_GUID_TYPE              1055
#define IDC_GUID_CREATE                 1055
#define IDC_GPTE_GUID                   1056
#define IDC_GPT_BACKUP                  1056
#define IDC_GPTE_START_LBA              1057
#define IDC_GPT_BACKUP2                 1057
#define IDC_GPT_FROM_BACKUP             1057
#define IDC_GPTE_LAST_LBA               1058
#define IDC_GPT_TOTAL_CHECK             1058
#define IDC_GPTE_ATTRIB                 1059
#define IDC_GPTE_NAME                   1060
#define IDC_FAT_JMP0                    1060
#define IDC_FAT_JMP1                    1061
#define IDC_GUID_TYPE                   1061
#define IDC_FAT_JMP2                    1062
#define IDC_GUID_CREATE_TYPE            1062
#define IDC_FAT_OEM_NAME                1063
#define IDC_FAT_BYTES_SECT              1064
#define IDC_GUID_PLUS_MINUS             1064
#define IDC_FAT_SECT_CLUSTER            1065
#define IDC_FAT_SECT_RESERVED           1066
#define IDC_FAT_FATS                    1067
#define IDC_FAT_ROOT_ENTRIES            1068
#define IDC_FAT_SECTORS                 1069
#define IDC_GPTE_NAME2                  1069
#define IDC_FAT_DESCRIPTOR              1070
#define IDC_FAT_SECT_FAT                1071
#define IDC_FAT_SECT_TRACK              1072
#define IDC_FAT_HEADS                   1073
#define IDC_FAT_HIDDEN_SECTS            1074
#define IDC_FAT_SECTORS_EXT             1075
#define IDC_FAT_DRV_NUM                 1076
#define IDC_FAT_RESERVED                1077
#define IDC_FAT_SIGNATURE               1078
#define IDC_FAT_SIG                     1078
#define IDC_FAT_SERIAL_NUM              1079
#define IDC_FAT_LABEL                   1080
#define IDC_FAT_FAT_TYPE                1081
#define IDC_EXFAT_RESERVED0             1082
#define IDC_DIR_TREE                    1084
#define ID_FAT32_INFO                   1088
#define IDC_LEAN_CRC                    1089
#define IDC_LEAN_MAGIC                  1090
#define IDC_LEAN_VERSION                1091
#define IDC_ENTRY_COUNT                 1091
#define IDC_LEAN_PRE_ALLOC              1092
#define IDC_NEW_INODE                   1092
#define IDC_LEAN_BLOCKS_BAND            1093
#define IDC_ENTRY_DISPLAY               1093
#define IDC_LEAN_CUR_STATE              1094
#define IDC_ORG_INODE                   1094
#define ID_LEAN_INSERT                  1095
#define IDC_LEAN_BLOCK_SIZE             1095
#define IDC_LEAN_GUID                   1096
#define IDC_LEAN_LABEL                  1097
#define IDC_LEAN_BLOCK_COUNT            1098
#define IDC_LEAN_FREE_BLOCKS            1099
#define IDC_LEAN_PRIMARY_LBA            1100
#define IDC_LEAN_BACKUP_LBA             1101
#define IDC_LEAN_BITMAP_LBA             1102
#define IDC_LEAN_ROOT_LBA               1103
#define IDC_LEAN_BAD_LBA                1104
#define IDC_LEAN_VERSION_DISP           1105
#define IDC_LEAN_PRE_ALLOC_DISP         1106
#define IDC_LEAN_BLOCKS_BAND_DISP       1107
#define ID_LEAN_COPY                    1108
#define IDC_JOURNAL_LBA                 1108
#define IDC_ENTRY_NAME                  1109
#define IDC_LEAN_BLOCK_SIZE_DISP        1109
#define IDC_ENTRY_EXT                   1110
#define ID_LEAN_DELETE                  1110
#define IDC_LAST_MOUNT                  1110
#define IDC_LEAN_NEXT_FREE              1110
#define IDC_ENTRY_ATTRIB                1111
#define IDC_LEAN_CAPABILITIES           1111
#define IDC_ENTRY_RESERVED              1112
#define IDC_LEAN_BITMAP_LBA2            1112
#define IDC_LEAN_BITMAP_CRC             1112
#define IDC_ENTRY_TIME                  1113
#define IDC_ENTRY_RESERVED1             1113
#define IDC_LEAN_ENCODING               1113
#define IDC_ENTRY_DATE                  1114
#define IDC_LEAN_ENCODING_DISP          1114
#define IDC_ENTRY_CLUSTER               1115
#define IDC_ENTRY_FILESIZE              1116
#define IDC_TIME_DISP                   1117
#define IDC_ENTRY_SECT_COUNT            1117
#define IDC_DATE_DISP                   1118
#define IDC_ENTRY_CRC                   1118
#define IDC_ENTRY_SEQU                  1119
#define IDC_ENTRY_MAGIC                 1119
#define IDC_ENTRY_LFN_ATTRIB            1120
#define IDC_ENTRY_EXT_COUNT             1120
#define IDC_ENTRY_CRC2                  1120
#define IDC_ENTRY_LFN_RESV              1121
#define IDC_ENTRY_RESVD                 1121
#define IDC_ENTRY_SFN_CRC               1122
#define IDC_ENTRY_IND_COUNT             1122
#define IDC_ENTRY_LFN_CLUST             1123
#define IDC_ENTRY_LINKS_COUNT           1123
#define IDC_ENTRY_LFN_NAME              1124
#define IDC_ENTRY_UID                   1124
#define IDC_SEQU_DISP                   1125
#define IDC_ENTRY_GID                   1125
#define IDC_ENTRY_ATTRBS                1126
#define IDC_ENTRY_ERROR_CODE            1126
#define IDC_ENTRY_ACC_TIME              1127
#define IDC_ENTRY_SCH_TIME              1128
#define IDC_ENTRY_MOD_TIME              1129
#define IDC_ENTRY_CRE_TIME              1130
#define IDC_ENTRY_FIRST_IND             1131
#define IDC_ENTRY_LAST_IND              1132
#define IDC_ENTRY_FORK                  1133
#define IDC_EXT_START                   1134
#define IDC_EXT_SIZE                    1135
#define IDC_CRC_UPDATE                  1136
#define IDC_ATTRIBUTE                   1137
#define IDC_MAGIC_UPDATE                1137
#define IDC_ACC_TIME_NOW                1138
#define IDC_BLOCK_UPDATE                1138
#define IDC_LIST                        1139
#define IDC_SCH_TIME_NOW                1139
#define IDC_FLAGS_B                     1139
#define IDC_THIS_BLOCK                  1139
#define IDC_EXT_SIZE2                   1139
#define IDC_MOD_TIME_NOW                1140
#define IDC_LEAN_TIME                   1140
#define IDC_D_RUN_LIST_B                1140
#define IDC_CRE_TIME_NOW                1141
#define IDC_LEAN_TIME_DISP              1141
#define IDC_S_CREATION_B                1141
#define IDC_DEL_TIME_NOW                1142
#define IDC_S_LAST_MOD_B                1142
#define IDC_RSVD_UPDATE                 1142
#define IDC_S_LAST_MOD_REC_B            1143
#define IDC_ENTRY_REC_LEN               1143
#define IDC_S_LAST_ACCESS_B             1144
#define IDC_ENTRY_NAME_LEN              1144
#define IDC_F_CREATION_B                1145
#define IDC_EXT_CRC                     1145
#define IDC_F_LAST_MOD_B                1146
#define IDC_F_LAST_MOD_REC_B            1147
#define IDC_SFS_TIMESTAMP               1148
#define IDC_F_LAST_ACCESS_B             1148
#define IDC_SFS_BLOCK_COUNT             1149
#define IDC_SFS_INDEX_SIZE              1150
#define IDC_SFS_TOTAL_BLOCKS            1151
#define IDC_SFS_MAGIC                   1152
#define IDC_SFS_VERSION                 1153
#define IDC_SFS_RESERVED_BLOCKS         1154
#define IDC_SFS_BLOCK_SIZE              1155
#define IDC_SFS_CRC                     1156
#define IDC_SFS_BLOCK_SIZE_DISP         1157
#define IDC_SFS_VERSION_DISP            1158
#define IDC_SFS_TIMESTAMP_DISP          1159
#define IDC_ENTRY_TYPE                  1160
#define IDC_ENTRY_CONT_COUNT            1161
#define IDC_ENTRY_START                 1162
#define IDC_ENTRY_END_BLOCK             1163
#define IDC_ENTRY_INDEX                 1164
#define IDC_ENTRY_FILELEN               1165
#define IDC_ENTRY_CONT_COUNT_DISP       1166
#define IDC_ENTRY_TIME_DISP             1167
#define ID_FYSOS_SIG                    1168
#define IDC_FYSOS_SIG_SIG               1168
#define IDC_FYSOS_SIG_BASE              1169
#define IDC_FYSOS_SIG_BOOTSIG           1170
#define IDC_UPDATE_SIG                  1171
#define IDC_UPDATE_BOOT_SIG             1172
#define IDC_SETTINGS_ERR_CNT            1172
#define IDC_UPDATE_SIG2                 1172
#define IDC_EMBR_SIG                    1173
#define IDC_UPDATE_SIG1                 1173
#define IDC_UPDATE_BASE                 1173
#define IDC_MBR_PATH                    1173
#define IDC_EMBR_ENTRY_OFFSET           1174
#define IDC_UPDATE_FREE                 1174
#define IDC_EMBR_PATH                   1174
#define IDC_EMBR_REMAINING              1175
#define IDC_UPDATE_RESVED               1175
#define IDC_EXTRACT_PATH                1175
#define IDC_EMBR_BOOT_SIG               1176
#define IDC_HELP_PATH                   1176
#define IDC_EMBR_DUMP                   1177
#define IDC_VIEWER_PATH                 1177
#define IDC_EMBR_PAGES                  1178
#define IDC_VIEWER_PATH2                1178
#define ID_EMBR_APPLY                   1179
#define IDC_EMBR_SIG0                   1180
#define IDC_EMBRE_START_LBA             1180
#define IDC_EMBR_CRC                    1181
#define IDC_EMBRE_SECTORS               1181
#define IDC_EMBR_ENTRIES                1182
#define IDC_EMBRE_OS_SIG                1182
#define IDC_EMBR_BOOT_DELAY             1183
#define IDC_EMBRE_DESCRIPT              1183
#define IDC_EMBR_RESV                   1184
#define ID_EMBRE_APPLY                  1184
#define IDC_EMBR_SIG1                   1185
#define IDC_EMBRE_FLAGS                 1185
#define IDC_EMBRE_SIG                   1186
#define IDC_BOOT_SIG_UPDATE             1186
#define IDC_EMBRE_CREATED               1187
#define IDC_RESV_CLEAR                  1187
#define IDC_FAT_SECT_FAT32              1187
#define IDC_EMBRE_LAST                  1188
#define IDC_SIG0_SET                    1188
#define IDC_FAT_EXT_FLAGS               1188
#define IDC_EMBRE_RESERVED              1189
#define IDC_SIG1_SET                    1189
#define IDC_FAT_FS_VERSION              1189
#define IDC_CRC_SET                     1190
#define IDC_FLAGS_SET                   1190
#define IDC_FAT_CLUST_NUM               1190
#define IDC_SIGNATURE_SET               1191
#define IDC_ESIG_SET                    1191
#define IDC_FAT_INFO_SECTOR             1191
#define IDC_INFO_SIG0                   1191
#define IDC_EMBR_CLEAR_RESV             1192
#define IDC_FAT_BACKUP_SECT             1192
#define IDC_INFO_SIG1                   1192
#define IDC_INFO_FREE_COUNT             1193
#define IDC_FAT_FS_VERSION_DISP         1193
#define IDC_EMBR_VERSION                1193
#define IDC_EDATE_NOW                   1193
#define IDC_INFO_NEXT_FREE              1194
#define IDC_EMBR_TOT_SECTORS            1194
#define IDC_EBOOT_NOW                   1194
#define IDC_INFO_SIG2                   1195
#define IDC_EMBR_VERSION_DISP           1195
#define IDC_RESERVED                    1196
#define IDC_UPDATE_TOT_SECTS            1196
#define IDC_INFO_SIG0_DISP              1197
#define IDC_SERIAL_UPDATE               1197
#define IDC_NUM_LBAS                    1197
#define IDC_PADDING                     1197
#define IDC_INFO_SIG1_DISP              1198
#define IDC_LEAN_MAGIC_UPDATE           1198
#define IDC_FAT_BACKUP_SECT_UPDATE      1198
#define IDC_FAT_BACKUP_SECT_RESTORE     1199
#define IDC_SET_SIZE                    1199
#define IDC_LEAN_CURRENT_STATE          1199
#define IDC_RESERVED_DISP               1200
#define IDC_SEQUENCE_NUM                1200
#define IDC_LEAN_CRC_UPDATE             1200
#define IDC_INSERT_VLABEL               1200
#define IDC_FAT32_ENTRY_RESV            1201
#define IDC_BLOCK_SIZE                  1201
#define IDC_RESERVED_DISP2              1201
#define IDC_FREE_BLOCKS_UPDATE          1201
#define IDC_FAT32_ENTRY_TENTH           1202
#define IDC_PATH_TABLE_SIZE             1202
#define IDC_BITMAP_CRC_UPDATE           1202
#define IDC_FAT32_ENTRY_TIME            1203
#define IDC_PATH_TABLE_LOC              1203
#define IDC_FAT32_ENTRY_DATE            1204
#define IDC_OPATH_TABLE_LOC             1204
#define IDC_FAT32_ENTRY_LAST_ACC        1205
#define IDC_ESC_SEQU                    1205
#define IDC_FAT32_ENTRY_CLUST           1206
#define IDC_ESC_SEQU_LEVEL              1206
#define IDC_FAT32_ENTRY_TIME_DISP       1207
#define IDC_UPDATE_TIME                 1208
#define IDC_UPDATE_DATE                 1209
#define IDC_FAT32_ENTRY_DATE_DISP       1210
#define IDC_UPDATE_LAST                 1211
#define IDC_FAT32_ENTRY_LAST_DISP       1212
#define IDC_SIG0                        1215
#define IDC_SIG1                        1216
#define IDC_VERSION                     1217
#define IDC_VERSION_DISP                1218
#define IDC_DATA_OFFSET                 1218
#define IDC_SECT_CLUST                  1219
#define IDC_TIME_STAMP                  1219
#define IDC_ENCRYPT_TYPE                1220
#define IDC_CREATOR                     1220
#define IDC_BITMAP_NUM                  1221
#define IDC_CREATOR_VERSION             1221
#define IDC_BITMAP_FLAGS                1222
#define IDC_CREATOR_HOST                1222
#define IDC_ROOT_ENTRIES                1223
#define IDC_ORIGINAL_SIZE               1223
#define IDC_BASE_LBA                    1224
#define IDC_CURRENT_SIZE                1224
#define IDC_ROOT_LSN                    1225
#define IDC_DISK_TYPE                   1225
#define IDC_DATA_LSN                    1226
#define IDC_CHECK_SUM                   1226
#define IDC_DATA_SECTORS                1227
#define IDC_SAVED_STATE                 1227
#define IDC_SECTOR_COUNT                1228
#define IDC_BITMAP_LSN                  1229
#define IDC_S_BITMAP_LSN                1230
#define IDC_LAST_CHKDSK                 1231
#define IDC_LAST_OPTIMIZE               1232
#define IDC_FLAGS                       1233
#define IDC_CRC                         1234
#define IDC_OSD1                        1234
#define IDC_REC_LEN                     1234
#define IDC_FLAGS_UPDATE                1235
#define IDC_NAME_LEN                    1235
#define IDC_SYMBOLIC_LINK               1235
#define IDC_ALLOC_SIZE                  1235
#define IDC_BITMAP_FLAGS_UPDATE         1236
#define IDC_NAME_FAT                    1236
#define IDC_BASE_FILE_REF               1236
#define IDC_GUID                        1237
#define IDC_NEXT_ATTRIB_ID              1237
#define IDC_LABEL                       1238
#define IDC_SLOT_TYPE                   1239
#define IDC_FAT_ENTRIES                 1240
#define IDC_SCRATCH                     1241
#define IDC_LAST_ACC                    1243
#define IDC_FILE_SIZE                   1244
#define IDC_FAT_CONT                    1245
#define IDC_LAST_ACC_TZ                 1245
#define IDC_NAME_CONT                   1246
#define IDC_CREATED                     1247
#define ID_VHD_APPLY                    1248
#define IDC_CREATED_MS                  1248
#define IDC_COOKIE                      1249
#define IDC_CREATED_TZ                  1249
#define IDC_FEATURES                    1250
#define IDC_CREATED_DISP                1250
#define IDC_DESCRIPTION                 1250
#define IDC_DUMP                        1251
#define IDC_MODIFIED_DISP               1251
#define IDC_LAST_ACC_DISP               1252
#define IDC_TIME_SHOW                   1252
#define IDC_CYL                         1253
#define IDC_HEAD                        1254
#define IDC_SECT                        1255
#define IDC_NEW_NAME                    1259
#define IDC_TYPE_PLAIN                  1260
#define IDC_TYPE_MBR                    1261
#define IDC_TYPE_EMBR                   1262
#define IDC_TYPE_GPT                    1263
#define IDC_RAW_FLAT                    1264
#define IDC_WITH_VHD                    1265
#define IDC_VDI_DYNAMIC                 1266
#define IDC_VDI_FLAT                    1267
#define IDC_TYPE_ISO9660                1268
#define IDC_PARTITIONS                  1269
#define IDC_NEW_PART_NAME               1270
#define IDC_TYPE_ISO_UDF                1270
#define IDC_SECTORS                     1271
#define IDC_PART_COUNT                  1272
#define IDC_COUNT_SPIN                  1273
#define IDC_BROWSE                      1274
#define IDC_ID_SIG_UPDATE               1275
#define IDC_ID_SIG_UPDATE2              1276
#define IDC_ID_ZERO_UPDATE              1276
#define IDC_STATUS                      1278
#define IDC_PROGRESS                    1279
#define IDC_SYS_ID                      1280
#define IDC_VOL_ID                      1281
#define IDC_DISK_TYPE_SET               1282
#define IDC_SET_ID                      1282
#define IDC_MBR_PATH_BRZ                1283
#define IDC_PUB_ID                      1283
#define IDC_DISK_TYPE_SET2              1283
#define IDC_VHD_CHECK_SUM               1283
#define IDC_EMBR_PATH_BRZ               1284
#define IDC_EXTRACT_PATH_BRZ            1285
#define IDC_TYPE                        1286
#define IDC_VIEWER_PATH_BRZ             1286
#define IDC_CD001                       1287
#define IDC_SYS_USE                     1288
#define IDC_PREP_ID                     1288
#define IDC_APP_ID                      1289
#define IDC_VAL_ID                      1289
#define IDC_BOOT_ID                     1290
#define IDC_COPY_ID                     1290
#define IDC_ABS_ID                      1291
#define IDC_BOOT_CAT_LBA                1291
#define IDC_BIB_ID                      1292
#define IDC_VOL_DATE                    1293
#define IDC_VAL_RESERVED                1293
#define IDC_MOD_DATE                    1294
#define IDC_YEAR                        1294
#define IDC_VAL_IDENT                   1294
#define IDC_EXP_DATE                    1295
#define IDC_MONTH                       1295
#define IDC_VAL_CRC                     1295
#define IDC_EFFECT_DATE                 1296
#define IDC_DAY                         1296
#define IDC_VAL_KEY55                   1296
#define IDC_HOUR                        1297
#define IDC_VAL_KEYAA                   1297
#define IDC_STRUCT_VER                  1298
#define IDC_MINUTE                      1298
#define IDC_DI_LOAD_SEG                 1298
#define IDC_SECOND                      1299
#define IDC_DI_SYS_TYPE                 1299
#define IDC_JIFFIES                     1300
#define IDC_DI_RESERVED                 1300
#define IDC_GMT_OFF                     1301
#define IDC_DI_LBA                      1301
#define IDC_DI_COUNT                    1302
#define IDC_LENGTH                      1303
#define IDC_EXTENT_LOC                  1304
#define IDC_DATA_LEN                    1305
#define IDC_UNIT_SIZE                   1307
#define IDC_GAP_SIZE                    1308
#define IDC_SEQU_NUM                    1309
#define IDC_FILENGTH                    1310
#define IDC_HARD_LINK_COUNT             1310
#define IDC_IDENT                       1311
#define IDC_ATTRIBS_OFF                 1311
#define IDC_IDENT_EXTRA                 1313
#define IDC_IDENT_EXTRA_S               1314
#define IDC_SECT_CLUSTER                1316
#define IDC_NUM_FATS                    1317
#define IDC_INFO                        1319
#define IDC_RELATIVE                    1324
#define IDC_BASE_SIZE_STR               1325
#define IDC_OLD_FAT                     1326
#define IDC_DUMP_STR                    1326
#define IDC_BASE_SIZE_STR2              1327
#define IDC_DONE                        1328
#define IDC_DONE2                       1329
#define IDC_COPY                        1329
#define IDC_NAME                        1330
#define IDC_AS_UTF8                     1331
#define IDC_AS_VALUE                    1332
#define IDC_AS_BYTES                    1333
#define IDC_ATTRIB_AS_UTF8              1334
#define IDC_ATTRIB_AS_VALUE             1335
#define IDC_ATTRIB_AS_BYTE              1336
#define IDC_ADD                         1337
#define IDC_DELETE                      1338
#define IDDONE                          1339
#define IDC_APPLY                       1340
#define IDC_FORCE_FORK                  1341
#define IDC_EXPAND                      1342
#define IDC_COLAPSE                     1343
#define IDC_INODE_COUNT                 1352
#define IDC_BLOCK_COUNT                 1353
#define IDC_R_BLOCK_COUNT               1354
#define IDC_BLOCKS_ALLOC                1354
#define IDC_FREE_BLOCK_COUNT            1355
#define IDC_FREE_INODE_COUNT            1356
#define IDC_FIRST_DATA_BLOCK            1357
#define IDC_LOG_BLOCK_SIZE              1358
#define IDC_LOG_FRAG_SIZE               1359
#define IDC_LOG_MAP_TABLE_LEN           1359
#define IDC_BLOCKS_GROUP                1360
#define IDC_LOG_PART_MAPS               1360
#define IDC_FRAGS_GROUP                 1361
#define IDC_INODES_GROUP                1362
#define IDC_MOUNT_TIME                  1363
#define IDC_WRITE_TIME                  1364
#define IDC_MOUNT_COUNT                 1365
#define IDC_MAX_MOUNT_COUNT             1366
#define IDC_MAGIC                       1367
#define IDC_STATE                       1368
#define IDC_FIXUP_OFF                   1368
#define IDC_ERROR_B                     1369
#define IDC_FIXUP_COUNT                 1369
#define IDC_MIN_REV_LEVEL               1370
#define IDC_LAST_OP_LSN                 1370
#define IDC_LAST_CHECK                  1371
#define IDC_S_TYPE                      1371
#define IDC_LAST_CHECK_INT              1372
#define IDC_S_LEN                       1372
#define IDC_CREATOR_OS                  1373
#define IDC_S_RES_FLAG                  1373
#define IDC_REV_LEVEL                   1374
#define IDC_S_NAME_LEN                  1374
#define IDC_UID                         1375
#define IDC_S_CONTENT_OFF               1375
#define IDC_GID                         1376
#define IDC_S_COMP_FLAG                 1376
#define IDC_DYN_REV                     1377
#define IDC_LINK_COUNT                  1377
#define IDC_S_ID                        1377
#define IDC_FIRST_INODE                 1378
#define IDC_BLOCKS                      1378
#define IDC_S_CREATION                  1378
#define IDC_INODE_SIZE                  1379
#define IDC_S_LAST_MOD                  1379
#define IDC_BLOCK_GR_NUM                1380
#define IDC_S_LAST_MOD_REC              1380
#define IDC_FEATURE_COMP                1381
#define IDC_S_LAST_ACCESS               1381
#define IDC_FEATURE_INCOMP              1382
#define IDC_S_DOS_PERM                  1382
#define IDC_FEATURE_RO_INCOMP           1383
#define IDC_S_MAX_VERSION               1383
#define IDC_VOLUME_NAME                 1384
#define IDC_S_VERSION                   1384
#define IDC_EXT2_GUID                   1385
#define IDC_S_CLASS_ID                  1385
#define IDC_ALGO_USAGE_BITMAP           1386
#define IDC_GROUPS                      1386
#define IDC_S_OWNER_ID                  1386
#define IDC_PRE_ALLOC_BLOCKS            1387
#define IDC_S_SECURITY_ID               1387
#define IDC_PRE_ALLOC_DIR_BLOCKS        1388
#define IDC_S_QUOTA                     1388
#define IDC_RESERVED_GDT_BLOCKS         1389
#define IDC_S_USN                       1389
#define IDC_BLOCK_BITMAP                1390
#define IDC_F_TYPE                      1390
#define IDC_INODE_BITMAP                1391
#define IDC_F_LEN                       1391
#define IDC_INODE_TABLE                 1392
#define IDC_F_RES_FLAG                  1392
#define IDC_FREE_BLOCKS_CNT             1393
#define IDC_F_NAME_LEN                  1393
#define IDC_FREE_INODES_COUNT           1394
#define IDC_F_CONTENT_OFF               1394
#define IDC_USED_DIR_CNT                1395
#define IDC_F_COMP_FLAG                 1395
#define IDC_UNUSED_INODE_CNT            1396
#define IDC_F_ID                        1396
#define IDC_NEXT                        1397
#define IDC_F_CREATION                  1397
#define IDC_GROUP_NUM                   1398
#define IDC_MODE                        1398
#define IDC_F_LAST_MOD                  1398
#define IDC_PREV                        1399
#define IDC_GENERATION                  1399
#define IDC_F_LAST_MOD_REC              1399
#define IDC_FSIZE                       1400
#define IDC_F_LAST_ACCESS               1400
#define IDC_ATIME                       1401
#define IDC_F_SEQU                      1401
#define IDC_CTIME                       1402
#define IDC_F_REF                       1402
#define IDC_MTIME                       1403
#define IDC_F_ALLOC_SIZE                1403
#define IDC_DTIME                       1404
#define IDC_F_FILE_SIZE                 1404
#define IDC_FILE_ACL                    1405
#define IDC_F_FLAGS                     1405
#define IDC_DIR_ACL                     1406
#define IDC_F_FILENAME_LEN              1406
#define IDC_F_ADDR                      1407
#define IDC_F_FILENAME                  1407
#define IDC_DOMODE                      1408
#define IDC_D_TYPE                      1408
#define IDC_INDIRECT                    1409
#define IDC_D_LEN                       1409
#define IDC_BLOCKS_FRAME                1410
#define IDC_D_RES_FLAG                  1410
#define IDC_DBL_INDIRECT                1411
#define IDC_D_NAME_LEN                  1411
#define IDC_TRP_INDIRECT                1412
#define IDC_D_CONTENT_OFF               1412
#define IDC_EXTENTS_FRAME               1413
#define IDC_D_COMP_FLAG                 1413
#define IDC_TIME_NOW                    1414
#define IDC_D_ID                        1414
#define IDC_ENTRIES                     1415
#define IDC_D_DATA_LEN                  1415
#define IDC_MAX                         1416
#define IDC_CUR_SIZE                    1416
#define IDC_D_DATA_OFFSET               1416
#define IDC_DEPTH                       1417
#define IDC_NEW_SIZE                    1417
#define IDC_D_INDEX_FLAG                1417
#define IDC_EXTENT_GEN                  1418
#define IDC_D_PADDING                   1418
#define IDC_DOFLAGS                     1419
#define IDC_D_START_VCN                 1419
#define IDC_D_LAST_VCN                  1420
#define IDC_D_RUN_LIST                  1421
#define IDC_D_ENGINE_NUM                1422
#define IDC_D_UNUSED                    1423
#define IDC_D_ALLOC_SIZE                1424
#define IDC_D_REAL_SIZE                 1425
#define IDC_EXFAT_JMP0                  1426
#define IDC_D_INITIAL_SIZE              1426
#define IDC_EXFAT_JMP1                  1427
#define IDC_EXFAT_JMP2                  1428
#define IDC_EXFAT_OEM_NAME              1429
#define IDC_EXFAT_PART_OFFSET           1430
#define IDC_EXFAT_TOTAL_SECTORS         1431
#define IDC_EXFAT_FIRST_FAT             1432
#define IDC_EXFAT_SECT_FAT              1433
#define IDC_EXFAT_DATA_REGION_LBA       1434
#define IDC_EXFAT_DATA_REGION_SIZE      1435
#define IDC_EXFAT_ROOT_CLUSTER          1436
#define IDC_EXFAT_SERIAL_NUM            1437
#define IDC_EXFAT_FS_VERSION            1438
#define IDC_EXFAT_FS_VERSION_DISP       1439
#define IDC_EXFAT_FLAGS                 1440
#define IDC_EXFAT_LOG_BYTES_SECT        1441
#define IDC_EXFAT_LOG_SECT_CLUSTER      1442
#define IDC_EXFAT_FATS                  1443
#define IDC_EXFAT_DRIVE_SEL             1444
#define IDC_EXFAT_PERCENT_HEAP          1445
#define IDC_EXFAT_RESERVED1             1446
#define IDC_EXFAT_LOG_BYTES_SECT_DISP   1447
#define IDC_SEC_COUNT                   1447
#define IDC_EXFAT_LOG_SECT_CLUSTER_DISP 1448
#define IDC_ATTRIB                      1448
#define IDLASTMOD                       1449
#define ID_EXFAT_UPDATE_BACKUP          1449
#define IDCREATED                       1450
#define ID_EXFAT_RESTORE_BACKUP         1450
#define IDLASTACC                       1451
#define ID_EXFAT_PARAM_SECT             1451
#define IDC_MODIFIED                    1452
#define IDC_MODIFIED_MS                 1453
#define IDC_MODIFIED_TZ                 1454
#define IDC_ENTRY_RESERVED0             1455
#define IDSFN_CLEAR0                    1456
#define IDFLAGS                         1457
#define IDC_ENTRY_RESERVED2             1458
#define IDLFN_CLEAR2                    1459
#define IDC_NAME_HASH                   1460
#define IDLFN_CLEAR3                    1461
#define IDC_ENTRY_RESERVED3             1462
#define IDC_VALID_DATA_LEN              1463
#define IDLFN_CLEAR4                    1464
#define IDC_ENTRY_RESERVED4             1465
#define IDC_HASH_UPDATE                 1466
#define IDDOATTRIB                      1467
#define IDC_BITMAP_BIT0                 1468
#define IDC_BITMAP_BIT1                 1469
#define IDC_BITMAP_BIT2                 1470
#define IDC_BITMAP_BIT3                 1471
#define IDC_BITMAP_BIT4                 1472
#define IDC_BITMAP_BIT5                 1473
#define IDC_BITMAP_BIT6                 1474
#define IDC_BITMAP_BIT7                 1475
#define IDC_SCROLLBAR                   1476
#define IDC_CLUSTER_TITLE               1477
#define ID_ERASE                        1478
#define IDC_CHAR_TITLE                  1479
#define IDC_CHAR_0                      1480
#define IDC_CHAR_1                      1481
#define IDC_CHAR_2                      1482
#define IDC_CHAR_3                      1483
#define IDC_UCHAR_0                     1484
#define IDC_UCHAR_1                     1485
#define IDC_UCHAR_2                     1486
#define IDC_UCHAR_3                     1487
#define IDC_ENTRY_GUID                  1488
#define ID_UPDATE_CODE                  1489
#define ID_VIEW_JOURNAL                 1490
#define ID_ENTRY                        1491
#define ID_COPY                         1492
#define ID_INSERT                       1493
#define ID_DELETE                       1494
#define ID_INSERT_FAT16                 1494
#define ID_APPLY                        1495
#define ID_CHECK                        1496
#define ID_INSERT_FAT17                 1496
#define ID_INSERT_FAT12                 1496
#define ID_CLEAN                        1497
#define ID_FORMAT                       1498
#define IDC_MFT_CLUSTER                 1499
#define ID_JOURNAL_INODE                1499
#define IDC_MFT_MIRROR_CLUST            1500
#define ID_SAVE_SUPER                   1500
#define IDC_CLUSTER_REC_SIZE            1501
#define ID_SAVE_SUPER2                  1501
#define ID_RESTORE_SUPER                1501
#define IDC_CLUSTER_INDEX_BLOCK         1502
#define ID_INSERT_SYMBOLIC              1502
#define IDC_CLUSTER_REC_SIZE_DISP       1503
#define IDC_SHOW_SYS_MFT                1504
#define ID_SEARCH                       1505
#define IDC_FIND_STR                    1505
#define IDC_CASE                        1506
#define ID_VIEW                         1506
#define IDC_TYPE_160K                   1507
#define IDC_TYPE_180K                   1508
#define IDC_TYPE_320K                   1509
#define IDC_TYPE_360K                   1510
#define IDC_TYPE_720K                   1511
#define IDC_TYPE_35_720K                1512
#define IDC_TYPE_1220K                  1513
#define IDC_TYPE_35_1440K               1514
#define IDC_TYPE_35_1720K               1515
#define IDC_TYPE_35_2880K               1516
#define IDC_TYPE_LOG_DRIVE              1517
#define IDC_VOLUME_LIST                 1518
#define IDC_BOUNDARY                    1519
#define IDC_JOURNAL                     1520
#define IDC_PRE_ALLOC_COUNT             1521
#define IDC_ROOT_SECTORS                1522
#define IDC_EAS_IN_INODE                1523
#define ID_CLEAR                        1524
#define IDC_PRE_ALLOC_COUNT2            1524
#define IDC_EXT_EXTENTS                 1524
#define IDC_ISO9660_NO_EMU              1525
#define IDC_ISO9660_144                 1526
#define IDC_ISO9660_120                 1527
#define IDC_ISO9660_288                 1528
#define IDC_ISO9660_HD                  1529
#define IDC_BOOTABLE                    1530
#define IDC_BOOT_FRAME                  1531
#define IDC_VAL_PLATFORM                1536
#define IDC_VAL_CRC_UPDATE              1537
#define IDC_VAL_KEY_UPDATE              1538
#define IDC_AVDP_TAG                    1538
#define IDC_DI_BOOTABLE                 1539
#define IDC_AVDP_LBA                    1539
#define IDC_DI_MEDIA                    1540
#define IDC_AVDP_LEN                    1540
#define IDC_DI_INSERT                   1541
#define IDC_AVDP_LBA_R                  1541
#define IDC_DI_EXTRACT                  1542
#define IDC_AVDP_LEN_R                  1542
#define IDC_UDF_TAG_ID                  1542
#define IDC_CLEAR_RESERVED              1543
#define IDC_UDF_TAG_VER                 1543
#define IDC_PART_TAG                    1543
#define IDC_UDF_TAG_CRC                 1544
#define IDC_PART_SEQ_NUM                1544
#define IDC_UDF_TAG_RSVD                1545
#define IDC_PART_FLAGS                  1545
#define IDC_UDF_TAG_SER_NUM             1546
#define IDC_PART_FLAGS_B                1546
#define IDC_UDF_TAG_DESC_CRC            1547
#define IDC_PART_NUMBER                 1547
#define ID_MOUNT_TIME                   1547
#define IDC_UDF_TAG_DESC_CRC_LEN        1548
#define IDC_PART_ACCESS_TYPE            1548
#define ID_WRITE_TIME                   1548
#define IDC_UDF_TAG_LOCATION            1549
#define IDC_PART_START_LBA              1549
#define ID_LAST_CHECK                   1549
#define IDC_PART_SECTOR_COUNT           1550
#define IDC_UDF_TAG_ID_B                1550
#define ID_LAST_CHECK_INT               1550
#define IDC_PART_ACCESS_TYPE_B          1551
#define ID_CREATOR_OS                   1551
#define IDC_LOG_TAG                     1552
#define ID_STATE                        1552
#define IDC_PART_CONTENTS               1553
#define ID_ERROR_B                      1553
#define IDC_PART_IMPLEMENT              1554
#define ID_MAGIC                        1554
#define IDC_LOG_SEQ_NUM                 1555
#define ID_FEATURE_COMP                 1555
#define IDC_LOG_INT_LBA                 1556
#define ID_FEATURE_INCOMP               1556
#define IDC_GPT_ENTRY_START             1556
#define IDC_LOG_INT_LEN                 1557
#define ID_FEATURE_RO_INCOMP            1557
#define IDC_GPT_ENTRY_START_S           1557
#define IDC_LOG_LOG_ID                  1558
#define IDC_DUMP_PREV                   1558
#define IDC_LOG_DOMAIN_ID               1559
#define IDC_DUMP_NEXT                   1559
#define IDC_EXTRA_COPY                  1559
#define IDC_LOG_IMPLEMENTATION_ID       1560
#define IDC_DUMP_FIRST                  1560
#define IDC_SHOW_DEL                    1561
#define IDC_DUMP_LAST                   1561
#define IDC_STATIC_NOTES                1562
#define IDC_VHD_GUID_UPDATE             1562
#define IDC_SHOW_DEL2                   1562
#define IDC_DEL_CLEAR                   1562
#define IDC_IGNORE_MT_GPT_ENTRIES       1563
#define IDC_SHOW_DEL3                   1563
#define IDC_SHOW_BYTES                  1564
#define IDC_SECT_SIZE_512               1566
#define IDC_SECT_SIZE_1024              1567
#define IDC_SECT_SIZE_2048              1568
#define IDC_SECT_SIZE_4096              1569
#define IDC_HEADER_SIZE                 1571
#define IDC_IMAGE_TYPE                  1572
#define IDC_OFFSET_BLOCKS               1573
#define IDC_OFFSET_DATA                 1574
#define IDC_UNUSED                      1575
#define IDC_DISK_SIZE                   1576
#define IDC_BLOCK_EXTRA                 1577
#define IDC_UUID                        1578
#define IDC_VDI_UUID_UPDATE             1579
#define IDC_VDI_SIG_UPDATE              1580
#define IDC_SNAP                        1581
#define IDC_VDI_SNAP_UPDATE             1582
#define IDC_LINK                        1583
#define IDC_VDI_LINK_UPDATE             1584
#define IDC_PARENT                      1585
#define IDC_VDI_PARENT_UPDATE           1586
#define IDC_DISK_SIZE_DISP              1587
#define IDC_DISK_SIZE_DISP2             1588
#define IDC_TYPE_DISP                   1588
#define IDC_NUM_BITMAPS                 1589
#define IDC_CASE_SENSITIVE              1590
#define IDC_HAS_SUP_BACKUP              1591
#define IDC_CREATED_CHANGE              1591
#define IDC_CREATED_CHANGE2             1592
#define IDC_LAST_CHANGE                 1592
#define IDC_SIZE_MEGS                   1592
#define IDC_FSZ_MAGIC                   1593
#define IDC_FSZ_VER_MAJ                 1594
#define IDC_FSZ_VER_MIN                 1595
#define IDC_FSZ_LOGSEC                  1596
#define IDC_FSZ_ENCTYPE                 1597
#define IDC_FSZ_FLAGS                   1598
#define IDC_FSZ_MAXMOUNTS               1599
#define IDC_FSZ_CURRMOUNTS              1600
#define IDC_FSZ_NUMSEC                  1601
#define IDC_FSZ_FREESEC                 1602
#define IDC_FSZ_ROOTFID                 1603
#define IDC_FSZ_FREESECFID              1604
#define IDC_FSZ_BADSECFID               1605
#define IDC_FSZ_INDEXFID                1606
#define IDC_FSZ_METAFID                 1607
#define IDC_FSZ_JOURNALFID              1608
#define IDC_FSZ_JOURNALHEAD             1609
#define IDC_FSZ_JOURNALTAIL             1610
#define IDC_FSZ_JOURNALMAX              1611
#define IDC_FSZ_ENCRYPT                 1612
#define IDC_FSZ_ENCHASH                 1613
#define IDC_FSZ_CREATEDATE              1614
#define IDC_FSZ_LASTMOUNTDATE           1615
#define IDC_FSZ_LASTUNMOUNTDATE         1616
#define IDC_FSZ_LASTCHECKDATE           1617
#define IDC_FSZ_UUID                    1618
#define IDC_FSZ_MAGIC2                  1619
#define IDC_FSZ_CHECKSUM                1620
#define IDC_FSZ_VERSION                 1621
#define IDC_FSZ_SECTSIZE                1622
#define IDC_FSZ_CREATEDATE_UPDATE       1623
#define IDC_FSZ_MOUNTED_UPDATE          1624
#define IDC_FSZ_UNMOUNTED_UPDATE        1625
#define IDC_FSZ_CHECKED_UPDATE          1626
#define IDC_FSZ_UUID_CREATE             1627
#define IDC_FSZ_SUPER_CRC_UPDATE        1628
#define IDC_CAPTION                     1628
#define IDC_FSZ_ENCRYPT_NAME            1629
#define IDC_ENTRY_BLOCK_COUNT           1629
#define IDC_FSZ_ENC_MASK_DO             1630
#define IDC_ENTRY_INODE                 1630
#define IDC_FREE_SIZE_STR               1631
#define IDC_ENTRY_THIS_BLOCK            1631
#define IDC_EDIT                        1632
#define IDC_ENTRY_PREV_INDIRECT         1632
#define IDC_ENTRY_NEXT_INDIRECT         1633
#define IDC_ENTRY_EXTENT_COUNT          1634
#define IDC_THIS_BLOCK_UPDATE           1635
#define IDC_RESV0_UPDATE                1636
#define IDC_RESV1_UPDATE                1637
#define IDC_RESV2_UPDATE                1638
#define IDC_ENTRY_RESERVED2_STATIC      1639
#define IDC_INDIRECT_STATUS             1640
#define IDC_SYMBOL_NAME                 1641
#define IDC_SYMBOL_NAME2                1642
#define IDC_SYMBOL_DATA                 1642
#define IDC_SHOW_HIDDEN                 1642
#define IDC_HIDDEN                      1643
#define IDC_UNDELETE                    1644
#define IDC_SPIN1                       1645
#define IDC_ENCODING                    1647
#define IDC_COUNT_LIST                  1648
#define ID_FILE_EXIT                    32771
#define ID_FILE_RECENTFILES_NORECENTFILES 32773
#define ID_SETTINGS                     32775
#define ID_FILE_RELOAD                  32776
#define ID_HELP_ABOUT                   32777
#define ID_TOOLS_RESIZE                 32778
#define ID_GET_DISK_IMAGE               32779
#define ID_ERASE_IMAGE                  32780
#define ID_TOOLS_ERASE_IMAGE            32781
#define ID_APPEND_VHD                   32782
#define ID_TOOLS_ADDHYBRIDCDROM         32783
#define ID_TOOLS_VIEWVDIHEADER          32784
#define ID_TOOLS_CREATE                 32785
#define ID_TOOLS_CREATE_INFO            32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        205
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1649
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
