/*             Author: Benjamin David Lunt
 *                     Forever Young Software
 *                     Copyright (c) 1984-2018
 *  
 *  This code is included on the disc that is included with the book
 *   FYSOS: The System Core, and is for that purpose only.  You have the
 *   right to use it for learning purposes only.  You may not modify it for
 *   redistribution for any other purpose unless you have written permission
 *   from the author.
 *
 *  You may modify and use it in your own projects as long as they are
 *   for non profit only and not distributed.  Any project for profit that 
 *   uses this code must have written permission from the author.
 */

#ifndef LIST_MBR
#define LIST_MBR

#pragma pack(1)

char strtstr[] = 
         "\nList MBR  v1.00.00  Forever Young Software -- (c) Copyright 1984-2015\n";

struct S_DISK_PACKET {
  bit8u  size;         // 10h or 18h
  bit8u  resv;         // 0
  bit16u num_blocks;   // max 7Fh
  bit16u offset;       // segmented address to transfer to
  bit16u segment;      //
  bit64u lba;          // lba
  bit64u phys_address; // (EDD-3.0, optional) 64-bit flat address of transfer buffer;
};                     // used if DWORD at 04h is FFFFh:FFFFh


bool check_big_disk(const bit8u);
bool read_sector(const bit8u, const bit64u, void *);
void display_new_line(const int);
void display_part_entrys(const int, const bit64u, const bit8u);


const char *fdisk_ids[] = {
	"Empty",
	"FAT12",
	"XENIX root",
	"XENIX usr",
	"FAT16 < 32M",
	"Extended",
	"FAT16",
	"HPFS/NTFS",
	"ATX",
	"ATX Bootable",
	"OS/2 Boot Manage",
	"W95 FAT32",
	"W95 FAT32 (LBA)",
	"*unknown*",
	"W95 FAT16 (LBA)",
	"W95 Ext'd (LBA)",
	"OPUS",
	"Hidden FAT12",
	"Compaq diagnostic",
	"*unknown*",
	"Hidden FAT16 < 32meg",
	"*unknown*",
	"Hidden FAT16",
	"Hidded HPFS/NTFS",
	"AST SmartSleep",
	"*unknown*",
	"*unknown*",
	"Hidded W95 FAT32",
	"Hidded W95 FAT32",
	"*unknown*",
	"Hidded W95 FAT36",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"NEC DOS",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"Plan 9",
	"*unknown*",
	"*unknown*",
	"PartitionMagic",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"Venix 80286",
	"PPC PRep Boot",
	"SFS",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"QNX4.x",
	"QNX4.x 2nd part",
	"QNX4.x 3rd part",
	"OnTrack DM",
	"OnTrack DM6 Aux",
	"CP/M",
	"OnTrack DM6 Aux",
	"OnTrackDM6",
	"EZ-DRIVE",
	"Golden Bow",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"Priam Edisk",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"SpeedStor",
	"*unknown*",
	"GNU HURD or Sys",
	"Novell Netware",
	"Novell Netware",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"DiskSecure Mult",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"PC/IX",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"Old Minix",
	"Minix / old Linux",
	"Linux swap",
	"Linux",
	"OS/2 Hidden C:",
	"Linux extended",
	"NTFS volume set",
	"NTFS volume set",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"Linux LVM",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"Amoeba",
	"Amoeba BBT",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"BSD/OS",
	"IBM Thinkpad hi",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"FreeBSD",
	"OpenBSD",
	"NeXTSTEP",
	"Darwin UFS",
	"NetBSD",
	"*unknown*",
	"Darwin boot",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"BSDI fs",
	"BSDI swap",
	"*unknown*",
	"*unknown*",
	"Boot Wizard hidden",
	"*unknown*",
	"*unknown*",
	"Solaris boot",
	"*unknown*",
	"*unknown*",
	"DRDOS/sec (FAT-",
	"*unknown*",
	"*unknown*",
	"DRDOS/sec (FAT-",
	"*unknown*",
	"DRDOS/sec (FAT-",
	"Syrinx",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"Non-FS data",
	"*unknown*",
	"*unknown*",
	"CP/M / CTOS / ",
	"Dell Utility",
	"BootIt",
	"*unknown*",
	"DOS access",
	"*unknown*",
	"DOS R/O",
	"SpeedStor",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"BeOS fs",
	"EFI GPT",
	"*unknown*",
	"*unknown*",
	"EFI (FAT-12/16/",
	"Linux/PA-RISC b",
	"SpeedStor",
	"DOS secondary",
	"*unknown*",
	"SpeedStor",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"*unknown*",
	"Linux raid auto",
	"LANstep",
	"BBT"
};

#endif // LIST_MBR
